name: Deploy to Netlify

# This section defines the events that will trigger the workflow.
on:
  push:
    branches:
      - main # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main # Trigger the workflow when a pull request is made to the main branch

# This section defines the jobs that the workflow will run.
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Specifies the runner. Here, it uses the latest Ubuntu version.

    steps:
      - uses: actions/checkout@v2
        # Checks out your repository under $GITHUB_WORKSPACE, so the workflow can access it.
        # Brings your code from repository to container(docker)
      - name: Set up Node.js
        uses: actions/setup-node@v2 # Sets up a specific version of Node.js on the runner.
        with:
          node-version: "18" # Set the Node.js version to 18.

      - name: Install dependencies
        run: npm install # Install the project dependencies.

      - name: Build
        run: npm run build # Build your React application.

      - name: Deploy to Netlify
        uses: netlify/actions/cli@master # This action integrates the Netlify CLI to deploy your site.
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }} # Your Netlify site ID, stored as a GitHub secret.
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }} # Your Netlify Auth token, stored as a GitHub secret.
        with:
          args: deploy --dir=build --prod # Commands passed to the Netlify CLI to deploy your site.`

